### PR TITLE
Fix progress signal to work when controls are hidden

### LINKED ISSUE #22: Fix progress signal
The current method of pulling the signal from the UI does not work when the controls are hidden.

An alternative that works consistently is to access the main video's progress property (selector: `video.html5-main-video`)

### PR DESCRIPTION
**Pull request by shyndman-augmented**
This PR addresses issue #22 by fixing the progress signal to work when the YouTube video controls are hidden.

## Changes
- Modified `readPlayheadPosition()` to first try to get the time directly from the video element using `video.html5-main-video.currentTime`
- Added fallback to the previous method (reading from `.ytp-time-current`) if the video element can't be found
- Added appropriate logging for both methods
- Updated function comments to reflect the changes

This approach ensures that the playhead position is consistently tracked regardless of whether the video controls are visible or hidden.

Fixes #22

### CODE REVIEW

File: src/llmop/youtube-watcher.ts [hunk 1]
```diff
@@ -288,7 +288,23 @@ function readPlayheadPosition(): number | null {
...
+      position: currentTime,
+    });
+    return currentTime;
+  }
+
+  logger.warn(
+    'Could not find video.html5-main-video element, falling back to UI method',
+  );
+
+  // Method 2 (fallback): Find the time display element in the UI
```
Comment (shyndman) [inline src/llmop/youtube-watcher.ts]: Please remove method 2 entirely. The fallback doesn't work well. We don't want it at all.
